### ISSUE TITLE
 Data type undefined

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#11]
Not sure if I'm missing something else but my `001-initial.sql` is bombing out today _completely_ which is now what happened yesterday.  Yesterday it was at least parsing some of the create table scripts.  I even tried to replace my create table script using one of your examples from your migrations folder, but same error.

This is after bringing down your latest **1.4.5**:

```js
CREATE TABLE public.city (
    city_id integer NOT NULL,
    name character varying NOT NULL,
    state_id integer
);
```

It looks like maybe it doesn't support character type yet or something?  I see **text** is supported in datatypes.d.ts but not character?

```js
Error: 🔨 Not supported 🔨 : Data type undefined

👉 pg-mem is work-in-progress, and it would seem that you've hit one of its limits.

*️⃣ Reconsituted failed SQL statement: CREATE TABLE "public"."city" ("city_id" "integer"   not null , "name" "character varying"   not null , "state_id" "integer"  )

👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:
```

**Aside**

Also BTW, when you ported that migrations code over from node-sqlite, did you also make that code more compatible with postgres so that it can parse postgres data types during migrations instead of relying on sqlite data types?

I am going to also suggest that you go one step further (not urgent but fairly) because it seems like you don't have this setup yet, which is to setup CI/CD for this project and show a pill on the main page so that I, the user knows that your tests for this are passing and that I have more confidence in using this lib.  That's not meant to be snarky, but being serious here.  Just a suggestion...

In fact, would you be cool with adding me as a collaborator which I _think_ would allow me to setup github actions for you and get CI running for you on this?

Also, I don't really want to use VSCode if I am to try to do any PRs or even try to run your stuff locally just to poke around. I am an JetBrains guy.  So I read that your "codebase only works in VsCode"?  I noticed after I did open it in WebStorm that `schema.ts` and `datatypes.ts` after doing `yarn`, had some types not resolving in those files.  For example in WebStorm I'm getting:

![Screen Shot 2020-12-12 at 12 25 23 AM](https://user-images.githubusercontent.com/338798/101977085-a3ca0080-3c10-11eb-8d12-096d4bbf63d3.jpg)

**Comment by oguimbal** [comment]
Okay my bad, that's because I released a breaking change in the parser as version `pgsql-ast-parser@1.5.0`, and pg-mem is picking it up (the current version depends on `^1.4.2`). I should have released it as a new major version.

I've fixed that.   `npm install pgsql-ast-parser@latest` should do the trick.

**Comment by oguimbal** [comment]
There already is CI setup:

![image](https://user-images.githubusercontent.com/8973947/101979902-6a6db100-3c61-11eb-9c4f-727bb1ca5dc9.png)

But this problem was not an issue that the CI could have caught, given that I released the incrimnated version of pgsql-ast-parser AFTER the last build of the CI pipeline happened.

**Comment by oguimbal** [comment]
As for the "vscode" part, it is OK to use this in another dev environment (the typing issues you're facing are also due to the faulty pgsql-ast-parser version).

I'm only suggesting vscode because i've setup HMR on unit tests, which requires an extension I've developped to be propertly integrated into the IDE. It allows me to have this kind of experience (that's thousands of requests being parsed), and [instant feedback when writing code](https://dev.to/oguimbal/zero-delay-development-unit-testing-iterations-1jk7)

![fast](https://user-images.githubusercontent.com/8973947/101980020-71e18a00-3c62-11eb-9950-26ad3b61fa39.gif)

**Comment by dschinkel** [comment]
Updated to pg-mem `^1.5.0` and it works!  I have another error/bug with timezone that I'll post an issue for next but look, we got an existing test passing using your in-memor DB yay!

![Screen Shot 2020-12-12 at 9 45 52 PM](https://user-images.githubusercontent.com/338798/102002623-e4cf1d00-3cc3-11eb-99d2-07cf3f63e507.jpg)

**Comment by oguimbal** [comment]
Nice 😀
