### ISSUE TITLE
Error: type "timestamp with time zone" does not exist

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#12]
looks like another type is not supported:
```js
Error: type "timestamp with time zone" does not exist
```
When my create table script which has this field type below in it, blows up:

```js
crafter_created_date timestamp with time zone NOT NULL,`
```

this is my core table so it's important that it be supported.

**Comment by oguimbal** [comment]
Fixed in `pg-mem@1.5.1`. 

However, it is to be noted that there is no difference between `timestamp with time zone` and `timestamp without time zone` ... they're just handled as js utc dates. I may implement this later, but I've never been comfortable with time zones (I live in a timezone where there is not much difference between UTC & me, which doesnt help me to care)
