### ISSUE TITLE
How to get connection details for Knex.js

### ISSUE THREAD

**Issue by AustinGil** [oguimbal/pg-mem#13]
I'm using knex.js to connect to my Postgres DB, but in testing, I would like to connect to the pg-mem DB. For that, I think I need to know the connection details or connection string. This is what knex.js uses

```js
  connection: {
    user: DB_USER,
    password: DB_PASS,
    database: DB_NAME,
    host: DB_HOST,
    port: DB_PORT,
  },
```

Is there a way to get these details from a pg-mem instance so knex will use that instead?

**Comment by oguimbal** [comment]
Hi ! Thanks for the report.

There is no networking involved with pg-mem, so it wont work using a host/port:  It should be done by using a pg-mem instance instead of an actual postgres connection inside Knex.js  (see [here](https://github.com/oguimbal/pg-mem/blob/master/src/adapters.ts#L143-L154) for an example of how it has been done for other libs)

I'm on vacations, but i'll investigate how to do that on Knex.js as soon as I return :)

(if you see how it could be done, PRs are open !)

**Comment by AustinGil** [comment]
Yeah, I kind of figured as much, but I didn't really know where to go from there. I tried exploring the `pg-mem` instance and some of the other connector utilities to see if something stuck out but did not come to any conclusions.

I guess I should describe my ideal scenario. It would be great if `pg-mem` provided the in memory DB that knex.js could then connect to. But from the examples I saw, it looked a bit more like `pg-mem` provided a sort of mock instance of the other connector types (typeorm, node-pg, etc). Is that right? Or would it be possible to configure the actual knex.js lib to connect to `pg-mem`, and then all the built-in `knex.js` stuff still works through that library?

Im reading through the example you shared, but I don't know if I'm qualified to understand entirely what is going on, hehe.

**Comment by obernardovieira** [comment]
Hi :wave: ,
Looking for the same, but different lib (sequelize in my case). I've looked at the links above and sequelize documentation to see if I can make the connection. But nothing yet. Any idea?

**Comment by oguimbal** [comment]
Hi! I'll have a look at sequelize as well when I return.

**Comment by AustinGil** [comment]
WHAAAT!?!? No way! That is awesome. I'm going to try it out now. Thank you
