### ISSUE TITLE
Column doesn't exist when creating table

### ISSUE THREAD

**Issue by Sven65** [oguimbal/pg-mem#147]
## Basic info

**pg-mem version**: 1.9.9
**jest version**: 27.0.4
**typeorm version**: 0.2.35

Reproduction link: https://gist.github.com/Sven65/5b462e2d2d4ded3d8f89d4792bf4fd6b

## Issue

When trying to create a table using pg-mem and typeorm entities, it fails as the column doesn't exist, with the following error message:

```
QueryFailedError: column "userid" does not exist

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: CREATE TABLE "userStats" ("userID" character varying(255) NOT NULL, CONSTRAINT "UQ_abb77da609fd701b7052a8b4531" UNIQUE ("userID"), CONSTRAINT "PK_abb77da609fd701b7052a8b4531" PRIMARY KEY ("userID"));
```

## Stacktrace

```ts
 at QueryFailedError.TypeORMError [as constructor] (src/error/TypeORMError.ts:7:9)
      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at PostgresQueryRunner.call (src/driver/postgres/PostgresQueryRunner.ts:258:19)
      at step (node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
      at Object.throw (node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
      at rejected (node_modules/typeorm/node_modules/tslib/tslib.js:115:51)
```

**Comment by pimartin** [comment]
I've got the same issue on a project.

Workaround: the error is not triggered when the UNIQUE constraint is removed.

**Comment by ashleighj** [comment]
Having the same problem:

```
QueryFailedError: column "deviceno" does not exist

Failed SQL statement: 
CREATE TABLE "public"."device" (
  ...[retracted]... ,
  "deviceNo" character varying NOT NULL, 
  ...[retracted]... , 
  CONSTRAINT "UQ_d9d3926bb8de75ed97230bae4a4" UNIQUE ("deviceNo"), 
  ...[retracted]...
);
```

**Comment by linsolas** [comment]
Hello all,

I have a similar issue on my side.
My entities are something like this:

```ts
@Entity()
export class MyKnowledge {
  @PrimaryColumn()
  application: string;

  @PrimaryColumn()
  language: string;

  @OneToMany(
    () => MyCategory, category => category.knowledge,
    { cascade: true }
  )
  categories: MyCategory[] | null;
}


@Entity()
export class MyCategory {
  @PrimaryColumn()
  id: string;

  @ManyToOne(
    () => MyKnowledge, knowledge => knowledge.categories,
    { primary: true, onUpdate: 'CASCADE', onDelete: 'CASCADE' }
  )
  knowledge: MyKnowledge;

  @OneToMany(
    () => MyCategory, category => category.parentCategory,
    { cascade: true, nullable: true }
  )
  subCategories: MyCategory[] | null;

  // Other "basic" fields
}
```
A "knowledge" is dedicated to a specific "application" for a given "language" (so the PK is based on `(application, language)`) and is composed of a list of "categories".

Now, when I start some tests using pg-mem, it fails with the following error:

```
    QueryFailedError: column "knowledgeapplication" does not exist

    �👉 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: CREATE TABLE "my_knowledge_category" (
      "id" character varying NOT NULL,
      "knowledgeApplication" character varying NOT NULL,
      "knowledgeLanguage" character varying NOT NULL,
      CONSTRAINT "PK_fca04a81c9ec0f8d9527180c80c" PRIMARY KEY ("id", "knowledgeApplication", "knowledgeLanguage")
    );

    �👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at QueryFailedError.TypeORMError [as constructor] (src/error/TypeORMError.ts:7:9)
      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at PostgresQueryRunner.<anonymous> (src/driver/postgres/PostgresQueryRunner.ts:258:19)
      at step (node_modules/tslib/tslib.js:143:27)
      at Object.throw (node_modules/tslib/tslib.js:124:57)
      at rejected (node_modules/tslib/tslib.js:115:69)
      at propagateAslWrapper (node_modules/async-listener/index.js:504:23)
      at node_modules/async-listener/index.js:541:70
```

It says that the column `knowledgeapplication` does not exist. If I modify the code of the `getColumn()` in my `node_modules/pg-mem/index.js` to force the column name to be `knowledgeApplication` (with a capital `A`) instead of `knowledgeapplication`, it does not throw the error!

I'm making additional investigation to know if there is a workaround for that, but that may help to find the issue in the code to solve this issue.

For information, I'm using typeorm v0.2.37 and pg-mem v1.9.17 (latest version as of today).

**Comment by linsolas** [comment]
More of my investigation. The problem is not on `pg-mem` but more on [`pgsql-ast-parser`](https://github.com/oguimbal/pgsql-ast-parser).
When it parses the constraints, it transforms the column name in lowercase.

If I take the SQL code generated by the @Sven65 code, and I put it on the [pg-mem playground](https://oguimbal.github.io/pg-mem-playground/), we can see that it fails saying that column `userid` does not exist:

```sql
CREATE TABLE "userStats" (
    "userid" character varying(255) NOT NULL,
    CONSTRAINT "UQ_abb77da609fd701b7052a8b4531" UNIQUE ("userid"),
    CONSTRAINT "PK_abb77da609fd701b7052a8b4531" PRIMARY KEY ("userid")
);
```

![image](https://user-images.githubusercontent.com/623217/131676765-1f51b5f2-4323-44c2-be87-d425171b92d8.png)

But with everything in lowercase, it works:

```sql
CREATE TABLE "userStats" (
    "userid" character varying(255) NOT NULL,
    CONSTRAINT "UQ_abb77da609fd701b7052a8b4531" UNIQUE ("userid"),
    CONSTRAINT "PK_abb77da609fd701b7052a8b4531" PRIMARY KEY ("userid")
);
```

![image](https://user-images.githubusercontent.com/623217/131676661-812b43b8-6d48-483c-a9a1-16ef670293b1.png)

I will create a ticket on `pgsql-ast-parser` repository...

**Comment by oguimbal** [comment]
Hi ! I just fixed it.

I still have several (unrelated) unit tests to fix, but it will be published with the next pg-mem version, hopefully a bit later this week.

Thanks for the feedback :)

**Comment by linsolas** [comment]
Thanks a lot @oguimbal! I've created the ticket here: https://github.com/oguimbal/pgsql-ast-parser/issues/61

Just for my curiosity, the fix is on `pg-mem` or on `pgsql-ast-parser`?
