### ISSUE TITLE
Typeorm doesn't connect to DB

### ISSUE THREAD

**Issue by matheus-silva-gaivota** [oguimbal/pg-mem#177]
# Describe the bug
I have tried to use `pg-mem` to test my application using `typeorm` and the version is `^0.2.41`, but it doesn't connect, someone could help me?

`pg-mem` returns the following message error:
```
QueryFailedError: ERROR: function current_database() does not exist
```

# To Reproduce
You just need to install `typeorm`, create an `entity` and try to connect on Database.

# pg-mem version
`^2.1.9`

**Comment by oguimbal** [comment]
Hi, this issue is a duplicate

- `pg-mem` only supports `typeorm <= 0.2.29` yet. Workaround for newer versions described in #81 
- The error you get is because of a missing function. pg-mem does not intend to implement many functions, but you can declare them yourself via [declareFunction()](https://github.com/oguimbal/pg-mem#custom-functions)

**Comment by nirajmchauhan** [comment]
The solution is really simple, just register a custom function `current_database`

```
db.public.registerFunction({
  name: 'current_database',
  args: [],
  returns: DataType.text,
  implementation: (x) => `hello world ${x}`,
});
```
