### ISSUE TITLE
Migrations format for compatibility with flyway

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#21]
I plan on using Flyway to pick up the migrations from pg-mem and deploy to my prod database and automate that in CI.  

Since pg-mem is using the code ported from node-sqlite, I don't know if this will work.  Is it possible to change the format for migrations for pg-mem to base it on the way flyway works just so that it'll be compatible?

https://dev.to/arojunior/the-best-and-easy-way-to-handle-database-migrations-version-control-pdg

So we'd need to be able to prefix migrations with V, etc.
https://flywaydb.org/documentation/concepts/migrations.html

So I'm proposing to tweak the code you ported over to have it work with that kind of prefix so that it's naturally compatible with flyway.

**Comment by oguimbal** [comment]
I won't be integrating this in pg-mem :( The sqlite migration thing was kind of okay because sqlite integrates it, but this is far too remote to be integrated in pg-mem (I don't want to maintain a replication of the entire database ecosystem)

Moreover, this looks very much like something that you could implement as a side library.

**Comment by dschinkel** [comment]
Yea I'm not looking to implement my own libs.  I'll have to figure out some scripting to rename these files or something.
