### ISSUE TITLE
SQL Migrations Not Working?

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#29]
So I know you wrote a test to test that ported sqlite migration code, saw that test in one of your commits.  But when I try this in my app, it's simply not working:

**InMemoryDB.ts**
```
const inMemoryDb = newDb();
inMemoryDb.public.none(fs.readFileSync(path.resolve(__dirname, 'migrations/001-initial.sql'), 'utf8'));
(async () =>await inMemoryDb.public.migrate())();
const skills = inMemoryDb.public.many("select * from skills where name = 'Swift'");
console.log('skills', skills); // prints []
```

the migrations folder is at the same level as **InMemoryDB.ts** and in that folder is:
```
001-initial.sql
002-add-skills.sql
```
`001-initial.sql` - definitely adds a skills table seeded with some initial skills

**002-add-skills.sql**
```
INSERT INTO skills VALUES ('Swift', 0);
INSERT INTO skills VALUES ('Objective-C', 0);
```

no idea here, thoughts?

**Comment by oguimbal** [comment]
No need to read 001-initial.sql, the migration will do that for you.

Moreover, the line `(async () =>await inMemoryDb.public.migrate())();` is effectively scheduling a migration, but triggers it "for later" (it dettaches a promise... use a linter, and you will get a warning on this line).

Thus, the 4th line is effectively executed BEFORE the migration.

This should work:

```typescript
const inMemoryDb = newDb();
await inMemoryDb.public.migrate();
const skills = inMemoryDb.public.many("select * from skills where name = 'Swift'");
console.log('skills', skills);
```

**Comment by dschinkel** [comment]
well I can't just do an await like you show, meaning you have to wrap it in an async function but thanks!  will try the changes out.

**Comment by dschinkel** [comment]
Got it working.  I'm going to do a PR with more tests and examples of it working.

**Comment by dschinkel** [comment]
@oguimbal I added a couple tests and some new behavior to your repo in my fork.  I don't see my new tests being run though after running them via `yarn test` for some reason.  It's not picking them up and I simply added a couple more tests to your `src/tests/migrate/migrate.spec.ts`

**Comment by oguimbal** [comment]
**Tests**  Some kind of building (transpiling, actually) is necessary given that it's TS, so no, it is not possible to run mocha directly on ts files. When you do that on your side, I suppose that you're using ts-node or something equivalent, which is transpiling TS for you. That's also what does Webpack. Kind of an equivalent way to do the same thing.

Moreover, [the current setup](https://github.com/oguimbal/pg-mem/blob/master/readme.md#-development) of pg-mem tests is using webpack because it's [way faster to code that way for me](https://dev.to/oguimbal/zero-delay-development-unit-testing-iterations-1jk7). That's a matter of choice.

**Ts compilation error**  I dont see this problem on my side ...

**Comment by dschinkel** [comment]
>it is not possible to run mocha directly on ts files
yes I'm using `ts-node`
