### ISSUE TITLE
Setup Example - but still some issues

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#32]
this works, just showing a full example now.

**InMemoryDB.ts**
```js
import path from 'path';
import { IBackup, IMemoryDb, newDb } from 'pg-mem';

let db: IMemoryDb;
let backup: IBackup;

export async function getDb(): Promise<IMemoryDb> {
  if (backup) {
    backup.restore();
    return db;
  }

  db = newDb();
  logFailedSQLStatements(db);
  await db.public.migrate({
    migrationsPath: path.join(__dirname, 'migrations'),
  });
  backup = db.backup();
  return db;
}

function logFailedSQLStatements(db) {
  db.on('query-failed', (sql) => {
    console.log('sql statement failed: ', sql);
  });
}
```

**DB.ts**
```js
import { getDb } from './pgMem/InMemoryDB';

...
async function queryInMemoryDB(queryTypeId, query) {
  let res;
  const db = await getDb();

  if (queryTypeId === queryType.MANY) {
    res = await db.public.many(query);
  }

  if (queryTypeId === queryType.ONE) {
    res = await db.public.one(query);
  }
  return res;
}

export default {
  queryDB,
  queryType,
};
```

In my tests I'm using it as so:
```js
beforeEach(async () => {
  const db = await getDb();
  db.backup().restore(); // had to call backup() to get to restore() now
  ...
});
```

**Comment by dschinkel** [comment]
shit it's 5am I'm going to bed.

**Comment by oguimbal** [comment]
1) No, it's not inneficient, look at the implementation of `newDb()` : it caches the underlying db object.

Moreover, as a side note, `const db = async () => await getDb()`  is equivalent to `const db = getDb;`  (without call... notice that there is no `()`)... so it's not very useful 🤔


2)  I'm sorry, but what you say is not possible:

Look at [this line](https://github.com/oguimbal/pg-mem/blob/4b8a36d53e481916ba4291e045ac6edae8682b31/src/schema.ts#L111) and you'll see that if `query-failed` hook is triggered (which it is: your log proves it), then an exception is thrown.

Thus, you **MUST** have a dettached promise somewhere, something eating your exceptions, or your test runner does not support async fixtures. This cannot be related to pg-mem. You'll have to create a simple public repo reproducing this issue to convince me otherwise.

**Comment by dschinkel** [comment]
I am using mocha.  Let me play with this and I'll get back to you, thank you!
