### ISSUE TITLE
Unexpected kw_do token: "do"

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#37]
Should I be able to run something like this via pg-mem?

```js
do $$
    DECLARE maxId integer;
    begin
        select max(id) from skills into maxId;
        select setval('skills_skill_id_seq',maxId);
end $$;
```

Error
```js
 '💀 Syntax error at line 406 col 1:\n' +
      '\n' +
      '  do\n' +
      '  ^\n' +
      'Unexpected kw_do token: "do". Instead, I was expecting to see one of the following:\n' +
      '\n' +
      '    - A "semicolon" token\n' +
      '    - A "kw_create" token\n' +
      '    - A "kw_create" token\n' +
      '    - A "kw_create" token\n' +
      '    - A "kw_create" token\n' +
      '    - A "kw_create" token\n' +
      '    - A "kw_with" token\n' +
      '    - A "word" token\n' +
      '    - A "kw_select" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "lparen" token\n' +
      '\n'
```

if not, I need to because I need to be able to reset the sequence on my table after I do inserts using `OVERRIDING SYSTEM VALUE` on a table with constraint `ADD GENERATED ALWAYS AS IDENTITY`

**Comment by dschinkel** [comment]
I've got many migrations that need to be able to do this.  For example, one migration that I already pushed to production:

```js
DO $$
    DECLARE crafter_community_atlanta_id integer;
        DECLARE atlanta_id integer;
        DECLARE location_atlanta_id integer;

    BEGIN
        select community.community_id into crafter_community_atlanta_id from community where community.name = 'Software Crafters - Atlanta';
        INSERT INTO city (name,state_id) VALUES ('Atlanta', 9);

        select city.city_id into atlanta_id from public.city where city.name = 'Atlanta';
        INSERT INTO location (
            city_id,
            state_id,
            country_id,
            name)
        VALUES (
                   atlanta_id,
                   9,
                   185,
                   'Atlanta, GA, USA'
               );

        select location.location_id into location_atlanta_id from location where location.name = 'Atlanta, GA, USA';
        INSERT INTO community_location (community_id, location_id) VALUES (crafter_community_atlanta_id, location_atlanta_id);
    END $$;
```

**Comment by oguimbal** [comment]
Hi !

pl/pgsql is not yet supported, and it will likely not be implemented anytime soon :(

I'm closing this in favor of https://github.com/oguimbal/pg-mem/issues/42 if you want to track it !

Thanks for the report

**Comment by dschinkel** [comment]
Thank you for confirming it's not a feature yet.

I do want to let you know that I'm hoping out of all the new issues you get, for the roadmap of pg-mem that you do prioritize SQL features that are core to being able to do migrations first.  Not being able to do more than just simple selects or inserts is critical to me being able to use pg-mem in a real application.

So instead of prioritizing stuff like "Get pg-mem to work with XYZ third party XYZ" this thing needs to get more mature in supporting more advenced features that are not honestly that advanced in terms of daily use of postgres such as subselects and pl/pgsql. Forget getting pg-mem working with this or that ORM, I'm pleading that when you have time and work on issues that you push those aside and work on the core support for running subselects, DO/End, etc.

Because right now I'm going to have to rewrite a bunch of migrations that flyaway was able to migrate just fine, like the code above and somehow dumb down my migration code if that's even possible into more crappy SQL if I even can to continue to be able to use pg-mem because it can't run a lot of things people rely on in basic SQL.

**Comment by oguimbal** [comment]
I understand your point. But in that matter, I'm chosing otherwise:

pg-mem cannot support all of the pgsql out of the box. It's just too big. I must do that  iteratively, adding features step by step.
So I have two choices:
1) Add features step by step, not supporting much ORMs.
2) Add ORM support first

If I chose (1), which you suggest, I'm concentrating on having less users for feeback, because most of those user wont be able to fully use pg-mem because it lacks a feature. And it will be a lot of time before I can say "ok, that's finished, lets start supporting ORMs". Thats a [V-model](https://en.wikipedia.org/wiki/V-Model_(software_development)), which has proven to be bad most of the time.

If I chose (2), I'll get users that use ORMs. Meaning a lot of potential users. This means that their DB schemas will be simpler, and the requests issued will always use the same SQL features (because they've been authored by ORMs).
Doing that is easier, as it allows to iterate step-by-step in an [agile](https://en.wikipedia.org/wiki/Agile_software_development) fashion. I prefer to do that.

ps: I have two companies to run, trust me, I also know how it feels like to lack time 😉
