### ISSUE TITLE
Support for MACADDR

### ISSUE THREAD

**Issue by gabssnake** [oguimbal/pg-mem#75]
Hello there!
We would love to have basic support for `MACADDR` type. It is somehow similar to `INET` in that you could always use `VARCHAR` if you only care for semantics, which is mostly our case (we don't use extensively the built-in functions).
Hope you are doing well,
Best,

**Comment by oguimbal** [comment]
Kind-of fixed in `pg-mem@1.8.0`  

I thought that trying to register every pg type is a bit out of scope... so I added a simple mechanism which allows you to [register new types](https://github.com/oguimbal/pg-mem#custom-types) which are mostly equivalent to already implemented types.

That said, this new version includes a refactoring of the syntax parser, which might have broken things (hopefully not)... could you pay a special attention and tell me if you see errors you didnt have before ?

**Comment by gabssnake** [comment]
That sounds great!
Yes, we have a comprehensive test suite, I'll run it through and get back to you with our results.

**Comment by gabssnake** [comment]
We have no regressions!

**Comment by oguimbal** [comment]
Thanks :)
