### ISSUE TITLE
parallel instance on pg-mem

### ISSUE THREAD

**Issue by AlexandreLoub** [oguimbal/pg-mem#94]
I want to run mocha in parallel and run pg-mem instances in parallel. The problem is that all jobs connect to the same db.
I think if there is a way to specify the name of the db, I can generate random names and there will bo no collision.

I use `createTypeormConnection`

**Comment by oguimbal** [comment]
Hi !

I'm affraid that will be a bit hard: It is not a limitation of pg-mem, but of Typeorm, which stores the created connection in static variables inside the library (from what I've seen).

On pg-mem side, each call to `newDb()` creates a brand new pg instance, which is isolated from the others.
So if this was not an issue with Typeorm, two calls to `newDb().adapters.createTypeormConnection()` would create two instances of Typerom bound to two distinct databases.

I'm closing this, since I dont see what I can do on my side to solve this: It works with pg-mem 😎
